version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8085:8080"      # Jenkins UI
      - "50000:50000"    # Agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

volumes:
  jenkins_home:
