version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8085:8080"   # Jenkins UI now available on http://localhost:8085
      - "50000:50000" # For Jenkins agent connections
    volumes:
      - jenkins_home:/var/jenkins_home
    user: "0"  # Run as root to avoid permission issues (safe for local dev)
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
    driver: local

